### ISSUE TITLE
リロード時にスクロールがトップに戻ってしまう

### ISSUE THREAD

**Issue by yosuke-furukawa** [recruit-tech/redux-pluto#110]
リロードした時にスクロール回帰がうまくいっていない。
特に外部のURLを見た後で戻った時にスクロール回帰できていない。
SSRでだけ実行すると動くのでCSR側でscrollをtopにしてしまっているように思える。
調査が必要。

**Comment by ka2jun8** [comment]
・SSRなら（Javascriptをオフにした状態で）ただのHTMLなのでスクロール位置は正しく回帰される。
・CSRでレンダリングされるとSPAなのでスクロールがトップに戻る。
・ちなみに同じコンテキスト内（/fooから/barへの遷移とか）だったら、
　react-router-scrollのuseScrollで同じスクロール位置に回帰できる。
・this._windowScrollTargetにスクロール位置を保管しておいて、遷移時に回帰するっぽい。
　https://github.com/taion/scroll-behavior/blob/master/src/index.js#L157-L167
・しかしリロードや外部のページから戻ってくるとthis._windowScrollTargetが空でscrollTopされる。
・react-routerがsessionStorageにhistoryのkeyでscroll位置を保管してあるので、
　client側でレンダリングし終えたあとでこの情報を使ってscroll位置を回帰するしかないかも。

さっき調べたことのメモです。
