### ISSUE TITLE
Greenkeeperのロックファイル更新で慢性的に失敗してしまう

### ISSUE THREAD

**Issue by dorayakikun** [recruit-tech/redux-pluto#386]
@kt3k 
最近、lockfileの更新で頻繁におちていますが、落ちている箇所がspawnしているためエラーの詳細が追えず対応が難しいです。

https://github.com/greenkeeperio/greenkeeper-lockfile/blob/master/lib/update-lockfile.js#L74

そこで、一時的に `exec` にエラーハンドリングを追加したfolkリポジトリを本流に混ぜ込みたいと思うのですが、いかがでしょう?

https://github.com/dorayakikun/greenkeeper-lockfile/blob/master/lib/update-lockfile.js#L74-L77

**Comment by kt3k** [comment]
あ、これなんですが、最近 greenkeeper が自分で lockfile を update してくれる機能がついたので、この npm module で自力であげる job 自体を消してしまった方が良いかもしれません. 自分の方で PR 投げます.

**Comment by dorayakikun** [comment]
お、なんと。
助かります... 🙏

**Comment by kt3k** [comment]
出したのですが、 audit job でコケてしまっています。
@orisano さんの https://github.com/siddharthkp/bundlesize/pull/295 が merge & release されれば直りそうなので, それ待ちになりそうです

**Comment by dorayakikun** [comment]
ありがとうございます！
ここでもまた問題になるんですね...
了解です！

**Comment by kt3k** [comment]
siddharthkp/bundlesize#295
これ結構時間かかりそうな雰囲気ですね・・・ audit を一時的に off にするか, bundlesize を一時的に外すかなどの対応をした方が良いかもですね・・・
`npm audit` に ignore list みたいなのがあると便利ですが・・・

**Comment by dorayakikun** [comment]
うーん、先日のCircleCIの設定に上書きで npm audit を無効化するとかですかね。

昨日調べたんですがCircleCIにはwarningを出す機能がないみたいなので、現状スマートな解法は無さそうです...
