### ISSUE TITLE
webpack v4 に上げる

### ISSUE THREAD

**Issue by yosuke-furukawa** [recruit-tech/redux-pluto#50]
当初は react-universal-component が v3 に依存していたため、一旦待機したが、 v4へのmigrateパスが見えたため、実施予定。

https://github.com/faceyspacey/webpack-flush-chunks#webpack-4-aggressive-code-splitting-support

また storybook がまだ v3 のため、二の足を踏んでいる。

**Comment by Tairyu** [comment]
#61

**Comment by yosuke-furukawa** [comment]
resolved
