### ISSUE TITLE
storybookを強化

### ISSUE THREAD

**Issue by yosuke-furukawa** [recruit-tech/redux-pluto#69]

**Comment by yosuke-furukawa** [comment]
現状空なので、ちゃんと書く。

**Comment by RyosukeCla** [comment]
結論としては storybook@4.0.0(stable) がリリースされるのを待つべし。

理由は簡単に言えば、redux-plutoのstorybookがうまく機能するようなstorybookのversionが無いから。詳細は以下。

`>alpha.2`だと、shared/components 以下の component を import するとエラーが起き、storybookは動かない。
エラーの内容は
```
Property value expected type of string but got null
```
で、[react docgen](https://github.com/storybooks/babel-plugin-react-docgen) の問題。詳しくは[ここ](https://github.com/storybooks/babel-plugin-react-docgen/issues/57#issuecomment-410988937)。

一方で、  [`<alpha.10`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.10) だと `babel-plugin-require-context-hook` の `require.context` が使えなくなるので、これもエラーが起きる。

**Comment by Tairyu** [comment]
一旦 PRがマージされたのでクローズ
